---
openapi: 3.0.0

info:
  title: Викторины API
  version: 1.0.0

servers:
  - description: Сервер для разработки
    url: http://localhost:8080/api/v1


paths:
  /quizzes:
    get:
      tags: [Quizzes]
      summary: Получить список всех викторин
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Quiz"
        "404":
          description: Викторины отсутствуют
    post:
      tags: [Quizzes]
      summary: Создать новую викторину
      requestBody:
        $ref: "#/components/requestBodies/QuizBody"
      responses:
        "201":
          description: Успешное создание
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Quiz"
        "400":
          description: Некорректное тело запроса

  /quizzes/{quizId}:
    parameters:
      - in: path
        name: quizId
        description: ID викторины
        required: true
        schema:
          type: integer
    get:
      tags: [Quizzes]
      summary: Получить информацию о викторине по ID

      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Quiz"
        "404":
          description: Викторина не найдена
    put:
      tags: [Quizzes]
      summary: Обновить информацию о викторине по ID
      requestBody:
        $ref: "#/components/requestBodies/QuizBody"
      responses:
        "200":
          description: Успешное обновление
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Quiz"
        "404":
          description: Викторина не найдена
    delete:
      tags: [Quizzes]
      summary: Удалить викторину по ID
      responses:
        "204":
          description: Успешное удаление
        "404":
          description: Викторина не найдена

  /quizzes/{quizId}/questions:
    parameters:
      - in: path
        name: quizId
        description: ID викторины
        required: true
        schema:
          type: integer
    get:
      tags: [Questions]
      summary: Получить список вопросов для викторины с указанным ID
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Question"
        "404":
          description: Викторина не найдена
    post:
      tags: [Questions]
      summary: Добавить новый вопрос в викторину с указанным ID

      requestBody:
        $ref: "#/components/requestBodies/QuestionBody"
      responses:
        "201":
          description: Успешное создание
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Question"
        "404":
          description: Викторина не найдена

  /questions/{questionId}:
    put:
      tags: [Questions]
      summary: Обновить информацию о вопросе в викторине с указанным ID
      parameters:
        - in: path
          name: questionId
          description: ID вопроса
          required: true
          schema:
            type: integer
      requestBody:
        $ref: "#/components/requestBodies/QuestionBody"
      responses:
        "200":
          description: Успешное обновление
    delete:
      tags: [Questions]
      summary: Удалить информацию о вопросе в викторине с указанным ID
      parameters:
        - in: path
          name: questionId
          description: ID вопроса
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Успешное удаление

  /questions/{questionId}/answers:
    # Общие параметры
    parameters:
      - in: path
        name: questionId
        description: ID вопроса
        required: true
        schema:
          type: integer
    get:
      tags: [Answers]
      summary: Получить список ответов вопроса с заданным ID

      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Answer"
    post:
      tags: [Answers]
      summary: Добавить ответ в вопрос с указанным ID

      requestBody:
        $ref: "#/components/requestBodies/AnswerBody"
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Answer"
  /questions/{questionId}/answers/{answerId}:

    # Общие параметры
    parameters:
      - in: path
        name: questionId
        description: ID вопроса
        required: true
        schema:
          type: integer
      - in: path
        name: answerId
        description: ID ответа
        required: true
        schema:
          type: integer

    get:
      tags: [Answers]
      summary: Получить ответ с указанным ID
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Answer'
    put:
      tags: [Answers]
      summary: Обновить ответ с указанным ID
      requestBody:
        $ref: "#/components/requestBodies/AnswerBody"
      responses:
        "200":
          description: Успешное обновление
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Answer"
        "404":
          description: Ответа с указанным ID не существует
    delete:
      tags: [Answers]
      summary: Удалить ответ с указанным ID
      responses:
        "204":
          description: Успешное удаление
        "404":
          description: Ответ с указанным ID не найден

components:
  requestBodies:

    QuizBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Quiz"

    QuestionBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Question"

    AnswerBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Answer"

  schemas:
    # Схема викторины
    Quiz:
      type: object
      properties:
        id:
          description: Уникальный идентификатор викторины
          type: integer
          example: 1
        title:
          description: Название викторины
          type: string
          example: Насколько хорошо ты знаешь шахматы!?
        description:
          description: Описание викторины
          type: string
          example: Шахматы - знакомая всем с детства игра, сочетающая в себе элементы искусства. Проверь свои знания и узнай, можно ли делить мир на черное и белое.
        created_at:
          description: Дата создания викторины
          type: string
          format: date
          example: 2023-06-28
        category:
          description: Категория викторины
          type: string
          example: Шахматы
        difficulty:
          description: Сложность викторины
          type: string
          example: Easy



    # Схема вопроса
    Question:
      type: object
      properties:
        id:
          description: Уникальный идентификатор вопроса
          type: integer
          example: 1
        text:
          description: Текст вопроса
          type: string
          example: Сколько насчитывается шахматных фигур?
        answers:
          description: Варианты ответа
          type: array
          items:
            $ref: "#/components/schemas/Answer"


    # Cхема вопроса
    Answer:
      type: object
      properties:
        id:
          description: Уникальный идентификатор ответа
          type: integer
          example: 1
        text:
          description: Содержимое ответа
          type: string
          example: шахматы НЕ являются видом спорта
        isCorrect:
          description: Указывает, является ли ответ правильным
          type: boolean
          example: false